// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: baskets.sql

package db

import (
	"context"
)

const GetBaskets = `-- name: GetBaskets :many
SELECT id, product_id, quantity FROM basket
ORDER BY id
`

func (q *Queries) GetBaskets(ctx context.Context) ([]Basket, error) {
	rows, err := q.query(ctx, q.getBasketsStmt, GetBaskets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basket
	for rows.Next() {
		var i Basket
		if err := rows.Scan(&i.ID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
